## Euler Problem 2
## Even Fibonacci Numbers

##Each New term in the fibonacci sequence is generated by adding the two previous terms,
##by starting with 1 and 2, the first ten terms will be:
## 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
## By considering the terms in the Fibonacci Sequence whose values 
## do not excede four million
## find the sum of the even-valued terms.

a = 1
b = 1
c = a + b
fibseq = []
d=0
while c < 4000000:
    fibseq.append(c)
    a = b
    b = c
    c = a + b
    if fibseq[d] % 2 != 0:
        fibseq[d] = 0
    d = d+1


print "\n Solution::"
print sum(fibseq)